customhost = "aws-project-db.c2wunnpg5ag5.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "niranjan"
customdb = "employee"
custombucket = "addemployee-aws-project"
customregion = "us-east-1"
